import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { SyncStatusBar } from './components/SyncStatusBar';
import { ConflictModal } from './components/ConflictModal';
import { TitleBar } from './components/TitleBar';
import { LoginScreen } from './components/LoginScreen';
import { Sidebar } from './components/Sidebar';
import { VaultView } from './components/VaultView';
import { TeamsView } from './components/TeamsView';
import { SettingsModal } from './components/SettingsModal';
import { ImportModal } from './components/ImportModal';
import { ExportModal } from './components/ExportModal';
import { ToastContainer } from './components/Toast';
import { useAppStore } from './store/app-store';
import { useAutoLock } from './hooks/useAutoLock';
import { useKeyboardShortcuts, shortcuts } from './hooks/useKeyboardShortcuts';
import { useSync } from './hooks/useSync';
function App() {
    const { isAuthenticated, isLocked, setVaults, setCurrentVault, setIsLocked, items, setItems, showImportModal, showExportModal, showConflictModal, conflicts, setConflicts, syncSettings, currentVault, currentView } = useAppStore();
    const [showSettings, setShowSettings] = useState(false);
    // Initialize Sync Hook
    const { sync, isConnected, isSyncing, lastSync, errors, itemsUpdated, itemsConflicted, resolveConflict } = useSync({
        vaultId: currentVault?.id,
        apiUrl: syncSettings.apiUrl,
        autoSync: syncSettings.autoSync,
        syncInterval: syncSettings.syncInterval
    });
    const handleResolveConflict = async (itemId, resolution) => {
        try {
            await resolveConflict(itemId, resolution);
            // Remove from local conflict list on success
            const newConflicts = conflicts.filter(c => c.itemId !== itemId);
            setConflicts(newConflicts);
        }
        catch (error) {
            console.error('Failed to resolve conflict:', error);
        }
    };
    const showLogin = !isAuthenticated || isLocked;
    // Auto-lock functionality
    useAutoLock();
    // Keyboard shortcuts
    useKeyboardShortcuts([
        {
            ...shortcuts.LOCK,
            handler: async () => {
                if (isAuthenticated && !isLocked) {
                    await window.electronAPI.lockVault();
                    setIsLocked(true);
                }
            },
        },
        {
            ...shortcuts.SETTINGS,
            handler: () => {
                if (isAuthenticated && !isLocked) {
                    setShowSettings(true);
                }
            },
        },
        {
            ...shortcuts.CLOSE_MODAL,
            handler: () => {
                setShowSettings(false);
            },
        },
    ]);
    useEffect(() => {
        // Load vaults when authenticated
        if (isAuthenticated && !isLocked) {
            loadVaults();
        }
    }, [isAuthenticated, isLocked]);
    const loadVaults = async () => {
        try {
            const vaults = await window.electronAPI.listVaults();
            setVaults(vaults);
            // Auto-create default vault if none exist
            if (vaults.length === 0) {
                const defaultVault = await window.electronAPI.createVault({
                    userId: '',
                    name: 'Personal',
                    type: 'personal',
                    encryptedKey: '', // Will be generated by backend
                });
                setVaults([defaultVault]);
                setCurrentVault(defaultVault);
            }
            else if (!currentVault) {
                // Select first vault by default
                setCurrentVault(vaults[0]);
            }
        }
        catch (error) {
            console.error('Failed to load vaults:', error);
        }
    };
    const handleImport = async (importedItems) => {
        try {
            setItems([...items, ...importedItems]);
            toast.success(`${importedItems.length} items imported successfully`);
        }
        catch (error) {
            console.error('Failed to import items:', error);
        }
    };
    return (_jsxs("div", { className: "h-screen flex flex-col bg-dark-900 overflow-hidden", children: [_jsx(TitleBar, {}), showLogin ? (_jsx(LoginScreen, {})) : (_jsxs("div", { className: "flex-1 flex flex-col overflow-hidden", children: [_jsxs("div", { className: "flex-1 flex overflow-hidden", children: [_jsx(Sidebar, {}), currentView === 'teams' ? _jsx(TeamsView, {}) : _jsx(VaultView, {})] }), _jsx(SyncStatusBar, { sync: sync, isConnected: isConnected, isSyncing: isSyncing, lastSync: lastSync, errors: errors, itemsUpdated: itemsUpdated, itemsConflicted: itemsConflicted })] })), _jsx(SettingsModal, { isOpen: showSettings, onClose: () => setShowSettings(false) }), _jsx(ImportModal, { isOpen: showImportModal, onClose: () => useAppStore.setState({ showImportModal: false }), onImport: handleImport, existingItems: items }), _jsx(ExportModal, { isOpen: showExportModal, onClose: () => useAppStore.setState({ showExportModal: false }), items: items }), _jsx(ConflictModal, { isOpen: showConflictModal, onClose: () => useAppStore.setState({ showConflictModal: false }), conflicts: conflicts, onResolve: handleResolveConflict }), _jsx(ToastContainer, {})] }));
}
export default App;
//# sourceMappingURL=App.js.map