import React, { useEffect, useState } from 'react'
import { SyncStatusBar } from './components/SyncStatusBar'
import { ConflictModal } from './components/ConflictModal'
import { TitleBar } from './components/TitleBar'
import { LoginScreen } from './components/LoginScreen'
import { Sidebar } from './components/Sidebar'
import { VaultView } from './components/VaultView'
import { SettingsModal } from './components/SettingsModal'
import { ImportModal } from './components/ImportModal'
import { ExportModal } from './components/ExportModal'
import { ToastContainer } from './components/Toast'
import { useAppStore } from './store/app-store'
import { useAutoLock } from './hooks/useAutoLock'
import { useKeyboardShortcuts, shortcuts } from './hooks/useKeyboardShortcuts'

function App() {
    const {
        isAuthenticated,
        isLocked,
        setVaults,
        setCurrentVault,
        setIsLocked,
        items,
        setItems,
        showImportModal,
        showImportModal,
        showExportModal,
        showConflictModal,
        conflicts,
        setConflicts,
    } = useAppStore()
    const [showSettings, setShowSettings] = useState(false)

    const handleResolveConflict = async (itemId: string, resolution: 'local' | 'server' | 'merge') => {
        // TODO: Implement actual resolution via sync service
        console.log('Resolving conflict:', itemId, resolution)

        // Remove from list
        const newConflicts = conflicts.filter(c => c.itemId !== itemId)
        setConflicts(newConflicts)
    }

    const showLogin = !isAuthenticated || isLocked

    // Auto-lock functionality
    useAutoLock()

    // Keyboard shortcuts
    useKeyboardShortcuts([
        {
            ...shortcuts.LOCK,
            handler: async () => {
                if (isAuthenticated && !isLocked) {
                    await window.electronAPI.lockVault()
                    setIsLocked(true)
                }
            },
        },
        {
            ...shortcuts.SETTINGS,
            handler: () => {
                if (isAuthenticated && !isLocked) {
                    setShowSettings(true)
                }
            },
        },
        {
            ...shortcuts.CLOSE_MODAL,
            handler: () => {
                setShowSettings(false)
            },
        },
    ])

    useEffect(() => {
        // Load vaults when authenticated
        if (isAuthenticated && !isLocked) {
            loadVaults()
        }
    }, [isAuthenticated, isLocked])

    const loadVaults = async () => {
        try {
            const vaults = await window.electronAPI.listVaults()
            setVaults(vaults)

            // Auto-create default vault if none exist
            if (vaults.length === 0) {
                const defaultVault = await window.electronAPI.createVault({
                    userId: '',
                    name: 'Personal',
                    type: 'personal',
                    encryptedKey: '', // Will be generated by backend
                })
                setVaults([defaultVault])
                setCurrentVault(defaultVault)
            } else {
                // Select first vault by default
                setCurrentVault(vaults[0])
            }
        } catch (error) {
            console.error('Failed to load vaults:', error)
        }
    }

    const handleImport = async (importedItems: any[]) => {
        try {
            // TODO: Save imported items to vault
            // For now, just update state
            setItems([...items, ...importedItems])
            console.log('Imported items:', importedItems)
        } catch (error) {
            console.error('Failed to import items:', error)
        }
    }

    return (
        <div className="h-screen flex flex-col bg-dark-900">
            <TitleBar />

            {showLogin ? (
                <LoginScreen />
            ) : (
                <div className="flex-1 flex flex-col overflow-hidden">
                    <div className="flex-1 flex overflow-hidden">
                        <Sidebar />
                        <VaultView />
                    </div>
                    <SyncStatusBar />
                </div>
            )}

            {/* Modals */}
            <SettingsModal isOpen={showSettings} onClose={() => setShowSettings(false)} />

            <ImportModal
                isOpen={showImportModal}
                onClose={() => useAppStore.setState({ showImportModal: false })}
                onImport={handleImport}
                existingItems={items}
            />

            <ExportModal
                isOpen={showExportModal}
                onClose={() => useAppStore.setState({ showExportModal: false })}
                items={items}
            />

            <ConflictModal
                isOpen={showConflictModal}
                onClose={() => useAppStore.setState({ showConflictModal: false })}
                conflicts={conflicts}
                onResolve={handleResolveConflict}
            />

            {/* Toast notifications */}
            <ToastContainer />
        </div>
    )
}

export default App
